server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_db?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.example.entity
  mapper-locations: classpath*:/mapper/**Mapper.xml
logging:
  level:
    com.example.mapper: debug